defaults:
  - default_config

ExperimentConfig:
  evaluate: true
  model_path: 
  evaluation_model_paths: [
                          "saved_models/22_02_2026__finished_PPO_Basis_thesis__args_working_main_5_3_1_update_880.pt",
                          # "models/finished_PPO_Basis_Thesis/finished_PPO_Basis_thesis.pt"
                          ]
  names: [
          "22_02_2026__finished_PPO_Basis_thesis__args_working_main_5_3_1_update_880",
          # "finished_PPO_Basis_Thesis"
         ]
  exp_name: "22_02_2026__finished_PPO_Basis_thesis__args_working_main_5_3_1_update_880"
  wandb_project_name: new_Evaluation
  # wandb_group_name: test_evaluation
  wandb_group_name: temp
  prod_mode: true

  seed:
  exact_seed: true
  
  dbg_deterministic_actions: false

  render: true
  render_all: false

  num_eval_episodes: 100
  num_parallel_eval_envs: 100
  num_parallel_selfplay_eval_games: 25        # Number of parallel environments 1 == 2 Selfplay envs
