defaults:
  - default_config

ExperimentConfig:
  evaluate: true

  unit_exploiters: false
  Unit_reward_per_exploiter: false
  zero_unit_bonus_for_main: false

  model_path: 
  evaluation_model_paths: [
                          "models/used_models/league_sp_conf_old_ppo_args_14_1_no_Bots_2__25envs_7_main_worker_focus_vs_finished_PPO_Basis_thesis_update_1670.pt",
                          # "models/finished_PPO_Basis_Thesis/finished_PPO_Basis_thesis.pt"
                          ]
  names: [
          "league_sp_conf_old_ppo_args_14_1_no_Bots_2__25envs_7_main_worker_focus_vs_finished_PPO_Basis_thesis_update_1670",
          # "finished_PPO_Basis_Thesis"
         ]
  exp_name: "league_sp_conf_old_ppo_args_14_1_no_Bots_2__25envs_7_main_worker_focus_vs_finished_PPO_Basis_thesis_update_1670_2"
  wandb_project_name: new_Evaluation
  # wandb_group_name: test_evaluation
  wandb_group_name: temp
  prod_mode: true

  seed: 
  exact_seed: true

  
  dbg_deterministic_actions: false

  capture_video: true
  render: true
  render_all: false

  num_eval_episodes: 100
  num_parallel_eval_envs: 100
  num_parallel_selfplay_eval_games: 25        # Number of parallel environments 1 == 2 Selfplay envs
