defaults:
  - default_config

ExperimentConfig:
  evaluate: true
  model_path: 
  evaluation_model_paths: [
                          "saved_models/06_03_2026__finished_PPO_Basis_thesis__league_training_2_1_update_1809.pt",
                          # "models/finished_PPO_Basis_Thesis/finished_PPO_Basis_thesis.pt"
                          ]
  names: [
          "06_03_2026__finished_PPO_Basis_thesis__league_training_2_1_update_1809",
          # "finished_PPO_Basis_Thesis"
         ]
  exp_name: "06_03_2026__finished_PPO_Basis_thesis__league_training_2_1_update_1809"
  wandb_project_name: testing_Evaluation
  prod_mode: true

  seed:
  exact_seed: true

  render: true
  render_all: false

  num_eval_episodes: 100
  num_parallel_eval_envs: 100
  num_parallel_selfplay_eval_games: 25        # Number of parallel environments 1 == 2 Selfplay envs
