defaults:
  - default_config

ExperimentConfig:
  evaluate: true
  model_path: 
  evaluation_model_paths: [
                          "league_models/debug_MainExploiter_vs_MainPlayer_initial_agent_exploiter_max_grad_norm_0_8_zwischenstand/MainExploiter/MainExploiter_0_update_200.pt",
                          # "models/finished_PPO_Basis_Thesis/finished_PPO_Basis_thesis.pt"
                          ]
  names: [
          "debug_MainExploiter_vs_MainPlayer_initial_agent_exploiter_max_grad_norm_0_8_zwischenstand",
          # "finished_PPO_Basis_Thesis"
         ]
  exp_name: "debug_MainExploiter_vs_MainPlayer_initial_agent_exploiter_max_grad_norm_0_8_zwischenstand_MainExploiter_0_update_200"
  wandb_project_name: new_Evaluation
  wandb_group_name: test_evaluation
  prod_mode: true

  seed:
  exact_seed: true

  render: true
  render_all: false

  num_eval_episodes: 100
  num_parallel_eval_envs: 100
  num_parallel_selfplay_eval_games: 25        # Number of parallel environments 1 == 2 Selfplay envs
